id: P88479480
initial_creation_type: ocr
source_metadata:
  volumes:
    224472d138074a78a1eed6e352a2c870:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
